server:
  port: 8085

logging:
  level:
    "[org.hibernate.sql]": debug
  file:
    path: logs

spring:
  jackson:
    default-property-inclusion: NON_NULL
  profiles:
    active: ${SPRING_PROFILES_ACTIVE:dev}

  jpa:
    defer-datasource-initialization: true
    hibernate:
      ddl-auto: ${SPRING_DDL_AUTO:create-drop}
    show-sql: true
