server:
  port: 8085

logging:
  level:
    '[org.hibernate.sql]': debug

spring:
  jackson:
    default-property-inclusion: NON_NULL
  profiles:
    active: prod

  jpa:
    defer-datasource-initialization: true
    hibernate:
      ddl-auto: create-drop
    show-sql: true

