apiVersion: apps/v1
kind: Deployment
metadata:
  name: shopapi-deployment
spec:
  selector:
    matchLabels:
      app: shopapi
  replicas: 1
  template:
    metadata:
      labels:
        app: shopapi
    spec:
      containers:
        - name: shopapi-container
          image: shopapi-shopapi:latest
          imagePullPolicy: Never
          ports:
            - containerPort: 8085
          env:   # Setting Enviornmental Variables
            - name: SPRING_PROFILES_ACTIVE
              valueFrom :
                configMapKeyRef :
                  name : app-config
                  key :  profile

            - name: SPRING_DDL_AUTO
              valueFrom :
                configMapKeyRef :
                  name : app-config
                  key :  hibernateDdlAuto

            - name: SPRING_DATASOURCE_URL   # Setting Database host address from configMap
              valueFrom :
                configMapKeyRef :
                  name : db-config
                  key :  dbUrl

            - name: SPRING_DATASOURCE_USERNAME  # Setting Database username from Secret
              valueFrom :
                secretKeyRef :
                  name : mysql-secrets
                  key :  username

            - name: SPRING_DATASOURCE_PASSWORD # Setting Database password from Secret
              valueFrom :
                secretKeyRef :
                  name : mysql-secrets
                  key :  password
            


---


apiVersion: v1 # Kubernetes API version
kind: Service # Kubernetes resource kind we are creating
metadata: # Metadata of the resource kind we are creating
  name: shopapi-svc
spec:
  selector:
    app: shopapi
  ports:
    - protocol: "TCP"
      port: 8085 # The port that the service is running on in the cluster
      targetPort: 8085 # The port exposed by the service
  type: NodePort # type of the service.